version: "3.9"  # optional since v1.27.0
services:
  api:
    image: raavgo/file_api
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/file_api/files

  worker:
    image: raavgo/worker
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/worker/files

  webserver:
    image: raavgo/webserver
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/webserver/files
